<?php

/**
 * @file
 * Theme registration for the Location module.
 */

use Drupal\Core\Template\Attribute;

/**
 * Implements hook_theme().
 */
function user_get_location_theme($existing, $type, $theme, $path) {
  return [
    'location_block' => [
      'variables' => [
        'attributes' => new Attribute(),
        'country' => '',
        'city' => '',
        'timezone' => '',
        'dateTime' => '',
      ],
    ],
  ];
}
